"""Add GIN search index

Revision ID: 517a2c6d9e7f
Revises: 10a4896ef3cf
Create Date: 2026-03-02 10:13:04.694461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '517a2c6d9e7f'
down_revision: Union[str, None] = '10a4896ef3cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('books', 'author',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index('ix_book_search_vector', 'books', [sa.text("to_tsvector('simple', title || ' ' || author)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_books_author'), 'books', ['author'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_author'), table_name='books')
    op.drop_index('ix_book_search_vector', table_name='books', postgresql_using='gin')
    op.alter_column('books', 'author',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('books', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
